// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATl6UoDtK7YkI3SbE0oCMgHdG4Q5vR8S4',
    appId: '1:175442159443:web:f34c3fa6ddf23bf6e4e3a6',
    messagingSenderId: '175442159443',
    projectId: 'ecomm-95604',
    authDomain: 'ecomm-95604.firebaseapp.com',
    databaseURL: 'https://ecomm-95604-default-rtdb.firebaseio.com',
    storageBucket: 'ecomm-95604.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALuJwG9CGJ5QHuMHmTQM9bKDYlxOCkLVk',
    appId: '1:175442159443:android:53ffbde84158f8f3e4e3a6',
    messagingSenderId: '175442159443',
    projectId: 'ecomm-95604',
    databaseURL: 'https://ecomm-95604-default-rtdb.firebaseio.com',
    storageBucket: 'ecomm-95604.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb6mQI9YHQkaml-bsCY5D-XCBUcU56JO0',
    appId: '1:175442159443:ios:5b59adef89c70ea6e4e3a6',
    messagingSenderId: '175442159443',
    projectId: 'ecomm-95604',
    databaseURL: 'https://ecomm-95604-default-rtdb.firebaseio.com',
    storageBucket: 'ecomm-95604.firebasestorage.app',
    iosBundleId: 'com.example.nileBrand',
  );
}
